# Jekyll configuration

title: 六月的天狼星
name: 六月的天狼星
name_en: June Sirius

# url is currently only used for the RSS feed in feed.xml
url: https://junesirius.github.io
baseurl: ""

# default date_format
date_format: 
  title: "%m-%d-%Y"
  archive: "%m-%d"
  categories: "%m-%d-%Y"
  tags: "%m-%d-%Y"

# Language
lan: "cn" 

# constant setups
paginate: 7
sidebar_len: 7

highlighter: rouge
markdown: kramdown
plugins: ["jekyll-paginate"]
google_analytics: G-7049S50VTD

exclude: ["README.md", "LICENSE", "*.bak", "*whole-novel.md", "assets/images/SPN"]

permalink: /:year/:month/:day/:title