# Jekyll configuration

title: 六月的天狼星
name: 六月的天狼星
name_en: June Sirius

# url is currently only used for the RSS feed in feed.xml
url: https://junesirius.github.io
baseurl: ""

# default date_format
date_format:
  title: "%m-%d-%Y"
  archive: "%m-%d"
  categories: "%m-%d-%Y"
  tags: "%m-%d-%Y"

# Language
lan: "cn"

# constant setups
sidebar_len: 7

highlighter: rouge
markdown: kramdown
google_analytics: G-7049S50VTD

exclude:
  - "README.md"
  - "LICENSE"
  - "pre-commit.sh"
  - ".pre-commit.py"
  - ".pre-commit-config.yaml"
  - "*.bak"
  - "*whole-novel.md"
  - "assets/images/**/*"

permalink: /:year/:month/:day/:title